### ISSUE TITLE
Execution of build fails due to missing `mistletoe.renders`

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#22]
After manual install of `pandas_sphinx_theme` (see #20), I get

```
$ jupyter-book build docs 
Running Sphinx v2.4.0
Adding copy buttons to code blocks...

Exception occurred:
  File "/home/john/anaconda3/lib/python3.7/site-packages/mistletoe/__init__.py", line 16, in <module>
    from mistletoe.renderers.base import BaseRenderer  # noqa: F401
ModuleNotFoundError: No module named 'mistletoe.renderers'
The full traceback has been saved in /tmp/sphinx-err-oxc7880n.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by chrisjsewell** [comment]
Yeh this is because you have the wrong mistletoe version, not the shiny new [mistletoe-ebp](https://mistletoe-ebp.readthedocs.io) 😄 

@choldgraf as a priority I think we need to get MyST-NB onto PyPi, plus CD from Travis (as I have setup for [Myst-Parser here](https://github.com/ExecutableBookProject/MyST-Parser/blob/40b4de4bdfd76b79a16e8b8a15f613dd85238176/.travis.yml#L41))

Then we can update the `setup.py` here, and make sure everyone's using the correct dependency versions on the stack.

Do you want me to do it?

**Comment by choldgraf** [comment]
Go for it. I won't be at my computer for a few hours

**Comment by chrisjsewell** [comment]
> Go for it. I won't be at my computer for a few hours

Just need to get the new jupyter-sphinx version released first: jupyter/jupyter-sphinx#106 (and also ideally pandas-dev/pydata-bootstrap-sphinx-theme#99)

**Comment by chrisjsewell** [comment]
@jstac @mmcky `myst-parser` and `myst-nb` are both now on PyPi, so everyone should be using `pip install myst-parser` / `pip install myst-nb` now, unless specifically wanting to develop on these packages

**Comment by choldgraf** [comment]
thanks for your hard work getting these packages out - it'll help us keep things more predictable

**Comment by choldgraf** [comment]
I think this one is now fixed, closing!
