### ISSUE TITLE
Warning: Could not lex literal_block as "python"

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/cli#60]
I get the above error for the following parameterized directive:
````
```{code-block} python
---
class: hide-output
---

!pip install --upgrade quantecon
```
````

**Comment by najuzilu** [comment]
Ah the answer is in the MyST-NB doc - see [here](https://myst-nb.readthedocs.io/en/latest/examples/jupyter_sphinx.html). I think we should add this information on the [JB Guide/Features/Execute and cache your notebook](https://beta.jupyterbook.org/use/execute.html). Or at the very least point to the MyST-NB page. What do you think @choldgraf?

**Comment by choldgraf** [comment]
Hmm - well, as a general rule I think we'd recommend using the myst-nb execution/cacheing as opposed to jupyter-sphinx so that you get the full notebook conversion etc, that just isn't implemented yet. Eventually we'll probably remove the `{execute}` functionality entirely. So I think this particular case is just that you're funding a "feature not implemented yet" bug :-)

**Comment by choldgraf** [comment]
This should now be fixed
