### ISSUE TITLE
Add a local preview option?

### ISSUE THREAD

**Issue by jstac** [ExecutableBookProject/cli#89]
It's not essential, since the notebook view gives a good indication of how the published material will look.  But nice to have nonetheless.

@chrisjsewell suggests  https://docs.python.org/3.8/library/webbrowser.html
@mmcky notes that this is used in Jupinx:  https://github.com/QuantEcon/jupinx/blob/master/jupinx/cmd/build.py#L185

**Comment by choldgraf** [comment]
I think something like this is a good idea. I am going to start off by just trying to make it more clear to users how they can preview the site after it is done building, just using prompts/docs instead of Python functions. e.g., I can preview the site by just running `chrome _build/html/index.html` so we can direct people in this way as a short-term solution.

**Comment by jstac** [comment]
That's probably even better for this initial stage because it's so simple and it shows people where the built pages are.

**Comment by choldgraf** [comment]
some of this should now be merged in by https://github.com/ExecutableBookProject/cli/pull/91 👍

**Comment by jstac** [comment]
Perfect, thanks!  Feel free to close.

**Comment by martinagvilas** [comment]
Hey! I'm having trouble finding the description of the local preview option in the documentation. Was it added in the end?

Just to give my two cents in this: the `chrome` command seems to be very dependent on your chrome installation and OS. In my case (macOS), to make it work I had to use `open -a 'google chrome' _build/html/index.html` where 'google chrome' can be replaced with your favorite browser. But this `open` command is also dependent on your OS and thus not a good option as default in the documentation.

A more generalizable option, in my opinion, is running: ` python -m http.server --directory _build/html/index.htm` I know it is still a python function, but users should have python installed anyways. The command in itself is readable even for those unfamiliar with it, and points to the built pages as well. And its behavior will not depend on your OS or browser installation. You still have to open the port manually, instead of the browser page popping out, but this was the case with jekyll as well and users didn't seem to mind.

An alternative with webbrowser is running `python -m webbrowser "file://{path}/_build/html/content/introduction/introduction.html"` but this requires adding the "file//" and specifying your path, which makes it a little bit more cumbersome in my opinion.

I just wanted to give those options as it took me a while to find the alternative of the `chrome` comand in my system.

**Comment by choldgraf** [comment]
@martinagvilas in this case it's not in the documentation, but should be in the printed message once the book is built. Basically, users just need to open the HTML file however they'd like (even double-clicking on it), so the message just tells them where `index.html` is and that's it. Do you think that it would be good to have in the documentation as well?

**Comment by martinagvilas** [comment]
@choldgraf I thought this issue referenced to the documentation, sorry about the confusion.

I don't see the harm in adding the local preview step to the documentation as well since it would be a very short paragraph and it's nice to have written down the whole workflow of building the jupyter-book somewhere (like in the previous version).

Also, regarding the message, why not in that case output the full path to the file and the `file://` added at the beginning, so that users can copy-paste it directly, like:

```
You can look at your book by opening this file in a browser:
    file://my_path/docs/_build/html/index.html
```
From what I understand, directly pasting `docs/_build/html/index.html` won't open the htmls.

**Comment by choldgraf** [comment]
> I don't see the harm in adding the local preview step to the documentation as well since it would be a very short paragraph and it's nice to have written down the whole workflow of building the jupyter-book somewhere (like in the previous version).

+1, good idea. Wanna add that to the docs in a PR? Or I can get to it later today or tomrorow.

> why not in that case output the full path to the file and the file:// added at the beginning, so that users can copy-paste it directly

hmmm - well the challenge there is that you couldn't copy-paste that into a browser unless it was an absolute path, since the working directory of the terminal is different from that of the browser. Maybe an absolute path would work, but then the path itself would be longer/messier.

**Comment by martinagvilas** [comment]
> +1, good idea. Wanna add that to the docs in a PR? Or I can get to it later today or tomrorow.
> 
> >

sure! I can try to make a PR with the changes

> What do you think? Too much info?

I like it! I think is not so much more info and the third option gives the user a faster way of visualizing the content.

> Another option is to clarify the language to be "You can look at your book by double-clicking this file to open in a browser"

I like it as well, but maybe this option can go in the documentation and not in the message? Given that its content won't change relative to the file.

I can also implement the last two changes in the PR.
